/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/**/*.blade.php',
        './resources/**/*.js',
        './resources/**/*.vue',
    ],
    theme: {
        extend: {
            "colors": {
                "tertiary-fixed": "#d9e3f9",
                "secondary-container": "#fed65b",
                "on-error-container": "#93000a",
                "surface-container-high": "#e6e8ea",
                "on-tertiary-fixed": "#121c2c",
                "background": "#f7f9fb",
                "on-secondary-fixed": "#241a00",
                "inverse-primary": "#adc7f7",
                "on-tertiary": "#ffffff",
                "on-error": "#ffffff",
                "success-emerald": "#10b981",
                "on-primary": "#ffffff",
                "on-surface": "#191c1e",
                "on-primary-container": "#86a0cd",
                "on-surface-variant": "#43474e",
                "secondary": "#735c00",
                "on-primary-fixed": "#001b3c",
                "primary": "#002045",
                "surface-container-low": "#f2f4f6",
                "on-secondary-fixed-variant": "#574500",
                "slate-text": "#1e293b",
                "surface-container": "#eceef0",
                "secondary-fixed-dim": "#e9c349",
                "surface-container-highest": "#e0e3e5",
                "error": "#ba1a1a",
                "error-rose": "#e11d48",
                "on-tertiary-fixed-variant": "#3d4759",
                "inverse-surface": "#2d3133",
                "surface-bright": "#f7f9fb",
                "info-blue": "#3b82f6",
                "primary-fixed": "#d6e3ff",
                "primary-container": "#1a365d",
                "inverse-on-surface": "#eff1f3",
                "tertiary-fixed-dim": "#bdc7dc",
                "secondary-fixed": "#ffe088",
                "surface": "#f7f9fb",
                "on-primary-fixed-variant": "#2d476f",
                "surface-container-lowest": "#ffffff",
                "tertiary-container": "#2c3647",
                "warning-amber": "#f59e0b",
                "error-container": "#ffdad6",
                "on-secondary-container": "#745c00",
                "outline-variant": "#c4c6cf",
                "primary-fixed-dim": "#adc7f7",
                "surface-dim": "#d8dadc",
                "outline": "#74777f",
                "surface-tint": "#455f88",
                "on-tertiary-container": "#959fb3",
                "on-background": "#191c1e",
                "surface-variant": "#e0e3e5",
                "tertiary": "#172131",
                "on-secondary": "#ffffff"
            },
            "borderRadius": {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem"
            },
            "spacing": {
                "md": "16px",
                "base": "4px",
                "margin-desktop": "32px",
                "margin-mobile": "16px",
                "xl": "40px",
                "sm": "8px",
                "lg": "24px",
                "gutter": "16px",
                "xs": "4px",
                "max-width": "1280px",
                "2xl": "64px"
            },
            "fontFamily": {
                "headline-lg": ["Geist"],
                "body-lg": ["Inter"],
                "body-md": ["Inter"],
                "label-sm": ["Inter"],
                "headline-lg-mobile": ["Geist"],
                "display": ["Geist"],
                "label-md": ["Inter"],
                "body-sm": ["Inter"],
                "headline-sm": ["Geist"],
                "headline-md": ["Geist"]
            },
            "fontSize": {
                "headline-lg": ["32px", { "lineHeight": "1.2", "fontWeight": "600" }],
                "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
                "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
                "label-sm": ["12px", { "lineHeight": "1", "fontWeight": "600" }],
                "headline-lg-mobile": ["24px", { "lineHeight": "1.2", "fontWeight": "600" }],
                "display": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
                "label-md": ["14px", { "lineHeight": "1", "letterSpacing": "0.01em", "fontWeight": "500" }],
                "body-sm": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
                "headline-sm": ["20px", { "lineHeight": "1.4", "fontWeight": "600" }],
                "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }]
            }
        },
    },
    plugins: [
        require('@tailwindcss/forms'),
        require('@tailwindcss/container-queries')
    ],
};
